import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { notFound } from 'next/navigation';

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3001').replace(/\/$/, '');
const servicePages = {
  'context-aware-decisions': { title: 'The next right move', eyebrow: '01 / Context-aware decisions', description: 'Choose the next move with the whole situation in view', detail: 'We assemble signals, constraints, history, and goals into decision surfaces with explicit risk and human fallback', outcomes: ['Context assembly', 'Decision policies', 'Risk-aware fallbacks'] },
  'mcp-agent-infrastructure': { title: 'Tools agents can rely on', eyebrow: '02 / Agent systems', description: 'Connect agents to operational tools through typed, governed interfaces', detail: 'We design typed MCP servers and evaluation harnesses with permissions, retries, traces, and recovery paths', outcomes: ['MCP tool contracts', 'Agent evaluation harnesses', 'Observable recovery'] },
  'long-term-memory': { title: 'Memory that earns trust', eyebrow: '03 / Long-term context', description: 'Carry the right context forward without blindly storing everything', detail: 'We make recall relevant, inspectable, and governed by the people who use the system', outcomes: ['Memory boundaries', 'Relevance scoring', 'Human correction loops'] },
  'industrial-agentic-systems': { title: 'Operational intelligence', eyebrow: '04 / Industrial AI', description: 'Coordinate people, machines, data, and decisions across the operating loop', detail: 'We place agents inside real workflows with clear authority, human handoffs, and outcome telemetry', outcomes: ['Operational orchestration', 'Human-in-the-loop controls', 'Outcome telemetry'] },
  'industrial-data-pipelines': { title: 'The industrial data spine', eyebrow: '05 / Data infrastructure', description: 'Move industrial data from live event streams to analysis-ready storage', detail: 'We connect Kafka, Flink, Spark, and MinIO into a dependable spine for operations and learning', outcomes: ['Event ingestion', 'Stream and batch processing', 'Durable object storage'] },
  'world-models-digital-twins': { title: 'Simulate before you commit', eyebrow: '06 / World models', description: 'Explore consequential decisions before committing real-world resources', detail: 'We make counterfactual futures visible, comparable, and easier to govern', outcomes: ['State estimation', 'Counterfactual rollouts', 'Confidence and fallback'] },
  'grounded-knowledge-systems': { title: 'Knowledge you can trace', eyebrow: '07 / Grounded knowledge', description: 'Retrieve the right evidence before generating an answer or recommendation', detail: 'We design RAG systems with embeddings, semantic search, and shared semantic layers that keep retrieval connected to source truth', outcomes: ['Retrieval architecture', 'Embedding and ranking strategy', 'Semantic contracts'] },
  'multi-agent-orchestration': { title: 'Coordinated agent systems', eyebrow: '08 / Multi-agent systems', description: 'Coordinate specialist agents around shared context, tools, and accountable decisions', detail: 'We design routing, shared state, evaluation, and human escalation for workflows where multiple agents genuinely add value', outcomes: ['Role and routing design', 'Shared context', 'Evaluation and escalation'] },
  'cloud-infrastructure': { title: 'Cloud foundations that scale', eyebrow: '09 / Cloud and networking', description: 'Build AWS infrastructure that stays observable, secure, and ready for the next release', detail: 'We design compute, containers, serverless functions, registries, and network boundaries as one dependable delivery system', outcomes: ['AWS architecture', 'Container and serverless delivery', 'Network and security boundaries'] },
} as const;
type ServiceSlug = keyof typeof servicePages;
export function generateStaticParams() { return Object.keys(servicePages).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = servicePages[slug as ServiceSlug]; return service ? { title: service.title, description: service.description, alternates: { canonical: `/services/${slug}` } } : {}; }
export default async function ServicePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const service = servicePages[slug as ServiceSlug]; if (!service) notFound();
  const structuredData = { '@context': 'https://schema.org', '@type': 'Service', name: service.title, description: service.description, provider: { '@type': 'ProfessionalService', name: 'Our Platform', url: siteUrl }, url: `${siteUrl}/services/${slug}` };
  return <main className="min-h-screen bg-cream px-6 py-10 text-text-primary dark:bg-charcoal dark:text-white"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><div className="mx-auto max-w-5xl"><Link href="/#services" className="inline-flex items-center gap-2 font-mono text-xs uppercase tracking-[0.18em] text-text-secondary hover:text-orange"><ArrowLeft size={15} /> Back to services</Link><div className="mt-24 max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.22em] text-orange">{service.eyebrow}</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.05em] md:text-7xl">{service.title}</h1><p className="mt-8 text-xl leading-8 text-text-secondary md:text-2xl">{service.description}</p><p className="mt-8 max-w-2xl text-base leading-8 text-text-secondary">{service.detail}</p></div><section className="mt-20 border-t border-border pt-8 dark:border-border-dark" aria-labelledby="outcomes-heading"><h2 id="outcomes-heading" className="text-2xl font-semibold">What this creates</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{service.outcomes.map((outcome) => <article key={outcome} className="rounded-2xl border border-border bg-white/60 p-5 dark:border-border-dark dark:bg-charcoal-light/50"><ArrowUpRight className="text-orange" size={18} aria-hidden="true" /><h3 className="mt-8 text-lg font-medium">{outcome}</h3></article>)}</div></section><Link href="/#contact" className="mt-14 inline-flex rounded-full bg-orange px-6 py-3 text-sm font-semibold text-white transition-transform hover:-translate-y-0.5">Start a conversation</Link></div></main>;
}
